# vim: sw=2

name: Build CI using docker images

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:

  rip-and-test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        #runner: ["ubuntu-24.04", "ubuntu-24.04-arm"]
        #debian_version:  ["bookworm", "trixie", "sid"]
        runner: ["ubuntu-24.04"]
        debian_version:  ["trixie"]
        include:
          - runner_arch: x64
            runner: ubuntu-24.04
          #- runner_arch: arm64
          #  runner: ubuntu-24.04-arm
    container:
      image: ghcr.io/${{ github.repository_owner }}/linuxcnc/build-container:${{ matrix.debian_version }}-${{ matrix.runner_arch }}-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo Number of CPUs: $(nproc)
        echo "$GITHUB_CONTEXT"
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        submodules: false
        fetch-depth: 1
    - name: Install dependencies
      run: |
        set -x
        .github/scripts/install-deps.sh
    - name: Build RIP GCC
      run: |
        set -x
        cd src
        ./autogen.sh
        ./configure --disable-check-runtime-deps --enable-werror
        make -O -j$((1+$(nproc))) default pycheck V=1
    - name: Test
      run: |
        set -x
        #Tests must be run as user, not root
        chown -R linuxcnc:linuxcnc .
        sudo -u linuxcnc scripts/rip-environment runtests -p

  package-arch:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        #runner: ["ubuntu-24.04", "ubuntu-24.04-arm"]
        #debian_version:  ["bookworm", "trixie", "sid"]
        runner: ["ubuntu-24.04"]
        debian_version:  ["trixie"]
        include:
          - runner_arch: x64
            runner: ubuntu-24.04
          #- runner_arch: arm64
          #  runner: ubuntu-24.04-arm
    container:
      image: ghcr.io/${{ github.repository_owner }}/linuxcnc/build-container:${{ matrix.debian_version }}-${{ matrix.runner_arch }}-latest
      # IPC_OWNER is needed for shmget IPC_CREAT
      # SYS_ADMIN is needed for shmctl IPC_SET
      options: --cap-add=IPC_OWNER --cap-add=SYS_ADMIN
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo Number of CPUs: $(nproc)
        echo "$GITHUB_CONTEXT"
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        submodules: false
        # "fetch-depth: 0" fetches all of history, this is needed by
        # our build system to determine the version from tags
        fetch-depth: 0
    - name: Add linuxcnc.org deb archive
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        .github/scripts/add-linuxcnc-repository.sh ${{ matrix.debian_version }}
        apt-get --quiet update
    - name: Build architecture-specific Debian packages
      env:
        DEBEMAIL: emc-developers@lists.sourceforge.net
        DEBFULLNAME: LinuxCNC Github CI Robot
        DEBIAN_FRONTEND: noninteractive
      run: |
        set -ex
        git config --global --add safe.directory .
        debian/configure
        debian/update-dch-from-git
        scripts/get-version-from-git | sed -re 's/^v(.*)$/\1/' >| VERSION; cat VERSION
        git diff
        apt-get -y build-dep --arch-only .
        debuild -us -uc --build=any
    - name: Install debian packages
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set -ex
        apt-get -y install ../*.deb --no-install-recommends
    - name: Test debian packages
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set -ex
        #Tests must be run as user, not root
        chown -R linuxcnc:linuxcnc .
        sudo -u linuxcnc ./scripts/runtests -p ./tests
    - name: Gather build artifacts
      run: |
        set -ex
        ARCH=$(dpkg --print-architecture)
        DIST=$(echo ${{ matrix.debian_version }} | cut -d : -f 2)
        OUTDIR="artifacts/${DIST}/${ARCH}"
        mkdir -p "$OUTDIR"
        cp -v $(find .. -maxdepth 1 -type f | LC_ALL=C sort) "$OUTDIR" || true
        (cd "$OUTDIR" && sha256sum * > SHA256SUMS.txt)
        echo "DIST=$DIST" >> "$GITHUB_ENV"
        echo "ARCH=$ARCH" >> "$GITHUB_ENV"
    - name: Compute artifact metadata
      id: meta
      run: |
        echo "dist=$(echo ${{ matrix.debian_version }} | cut -d : -f 2)" >> $GITHUB_OUTPUT
        echo "arch=$(dpkg --print-architecture)" >> $GITHUB_OUTPUT
    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: linuxcnc-${{ steps.meta.outputs.dist }}-${{ steps.meta.outputs.arch }}
        path: artifacts/${{ steps.meta.outputs.dist }}/${{ steps.meta.outputs.arch }}
        if-no-files-found: error