# vim: sw=2

name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

permissions:
  contents: read #  to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  DEBIAN_FRONTEND: noninteractive

jobs:

  htmldocs:
    runs-on: ubuntu-24.04
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo Number of CPUs: $(nproc)
        echo "$GITHUB_CONTEXT"
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        submodules: false
        fetch-depth: 1
    - name: Install dependencies
      run: |
        set -x
        .github/scripts/install-deps.sh
    - name: Build HTML docmentation
      run: |
        set -x
        .github/scripts/build-doc.sh
    - name: Verify no untracked or modified files after build
      run: |
        #*.po and documentation.pot are modifyed by build. Ignore them for now.
        .github/scripts/verify-clean-repo.sh ':(exclude)docs/po/*.po' ':(exclude)docs/po/documentation.pot'
    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: linuxcnc-doc
        path: docs/build/html
        if-no-files-found: error

  #This build step publishes a package as a container
  #Thanks to https://www.kenmuse.com/blog/universal-packages-on-github-with-oras/
  #Download the resulting package built for master using:
  #oras pull ghcr.io/linuxcnc/linuxcnc/doc-html:master
  htmldocs-package:
    runs-on: ubuntu-24.04
    needs: htmldocs
    #Run on branch master / 2.9 or if the commit is tagged
    if: github.ref_name == 'master' || github.ref_name == '2.9' || startsWith(github.ref, 'refs/tags/')
    permissions:
      packages: write # to create containers
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo Number of CPUs: $(nproc)
        echo "$GITHUB_CONTEXT"
    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        name: linuxcnc-doc
        path: html
    - name: Use oras
      uses: oras-project/setup-oras@v2
      with:
        version: 1.3.1
    - name: Publish package
      run: |
        set -x
        tar -czf doc-html.tar.gz html
        TAG=${{github.ref_name}} #This is either the tag or branch name
        echo ${{ secrets.GITHUB_TOKEN }} | oras login --username ${{ github.actor }} --password-stdin ghcr.io
        oras push ghcr.io/${{ github.repository_owner }}/linuxcnc/doc-html:${TAG} --artifact-type application/vnd.pkgw doc-html.tar.gz

