# vim: sw=2

name: Build Docker

on:
  workflow_dispatch:
  schedule:
     - cron: "18 0 * * 1"

permissions:
  contents: read  # to fetch code (actions/checkout)
  packages: write # to create docker images

jobs:
  build-docker:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        #runner: ["ubuntu-24.04", "ubuntu-24.04-arm"]
        #debian_version:  ["bookworm", "trixie", "sid"]
        runner: ["ubuntu-24.04"]
        debian_version:  ["trixie"]
        include:
          - runner_arch: amd64
            runner: ubuntu-24.04
          #- runner_arch: arm64
          #  runner: ubuntu-24.04-arm
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo Number of CPUs: $(nproc)
        echo "$GITHUB_CONTEXT"
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        submodules: false
        fetch-depth: 1
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v7
      with:
        context: .
        file: .github/docker/Dockerfile
        build-args: |
            BASE_IMAGE=debian:${{ matrix.debian_version }}
        push: true
        outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=LinuxCNC build image
        tags: ghcr.io/${{ github.repository_owner }}/linuxcnc/build-container:${{ matrix.debian_version }}-${{ matrix.runner_arch }}-latest